apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-auth
  namespace: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-auth
  template:
    metadata:
      labels:
        app: mongodb-auth
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: MONGODB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: MONGODB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "auth"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-auth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-auth
  namespace: ecommerce-app
spec:
  selector:
    app: mongodb-auth
  ports:
  - port: 27017
    targetPort: 27017