apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-auth-pvc
  namespace: ecommerce-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-product-pvc
  namespace: ecommerce-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-order-pvc
  namespace: ecommerce-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi