apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: NODE_ENV
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: MONGODB_CONNECTION_STRING_PRODUCT
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: RABBITMQ_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce-app
spec:
  selector:
    app: product-service
  ports:
  - port: 3001
    targetPort: 3001