apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-app
data:
  NODE_ENV: "production"
  AUTH_SERVICE_URL: "http://auth-service:3000"
  PRODUCT_SERVICE_URL: "http://product-service:3001"
  ORDER_SERVICE_URL: "http://order-service:3002"
  API_GATEWAY_URL: "http://api-gateway:3003"
  RABBITMQ_URL: "amqp://rabbitmq:5672"