apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: NODE_ENV
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: MONGODB_CONNECTION_STRING_AUTH
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: JWT_SECRET_KEY
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: RABBITMQ_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecommerce-app
spec:
  selector:
    app: auth-service
  ports:
  - port: 3000
    targetPort: 3000